[package]
name = "pdf-editor-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.29"
cocoa = "0.26"
core-graphics-types = "0.2"
objc = "0.2"
