[package]
name = "pdf-editor-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pdf-editor-render = { path = "../render" }
pdf-editor-cache = { path = "../cache" }
